// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUU5Bh3UTJ9LqJGlG_X8qR4Pj9O5fsW6M',
    appId: '1:795587268194:web:7af39cc977cb0fb24b8b3b',
    messagingSenderId: '795587268194',
    projectId: 'flutter-e-library-45a9e',
    authDomain: 'flutter-e-library-45a9e.firebaseapp.com',
    storageBucket: 'flutter-e-library-45a9e.appspot.com',
    measurementId: 'G-9KFCWDKHL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtJ3Nfzix0OxjJcMICe2EM6z6bdCF3jWE',
    appId: '1:795587268194:android:2b112a9608a903c14b8b3b',
    messagingSenderId: '795587268194',
    projectId: 'flutter-e-library-45a9e',
    storageBucket: 'flutter-e-library-45a9e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUU5Bh3UTJ9LqJGlG_X8qR4Pj9O5fsW6M',
    appId: '1:795587268194:web:60afc110195b0bd44b8b3b',
    messagingSenderId: '795587268194',
    projectId: 'flutter-e-library-45a9e',
    authDomain: 'flutter-e-library-45a9e.firebaseapp.com',
    storageBucket: 'flutter-e-library-45a9e.appspot.com',
    measurementId: 'G-9FQ1MWST27',
  );
}
